FROM maven
LABEL authors="zgeorgan"
RUN mkdir /project
COPY . /project
WORKDIR /project
EXPOSE 8080
RUN mvn clean compile package
ENTRYPOINT ["java", "-jar", "/project/target/smartcalc-0.0.1-SNAPSHOT.jar"]